pipeline {
    agent any

    environment {
        AWS_CREDENTIALS_ID = 'aws-credentials'
        S3_BUCKET = 's3chatbot.com'
        BUILD_DIR = 's3chatbot-frontend/build'
        REACT_APP_DIR = 's3chatbot-frontend'
        AWS_REGION = 'us-east-1'
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Repository already checked out by Declarative Checkout SCM"
            }
        }

        stage('Install Dependencies') {
            steps {
                sh "cd ${REACT_APP_DIR} && npm install"
            }
        }

        stage('Build') {
            steps {
                sh "cd ${REACT_APP_DIR} && npm run build"
            }
        }

        stage('Deploy to S3') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                    sh "aws s3 sync ${BUILD_DIR} s3://${S3_BUCKET} --delete --acl public-read --region ${AWS_REGION}"
                }
            }
        }
    }
}