pipeline {
    agent any

    environment {
        AWS_CREDENTIALS_ID = 'aws-credentials'
        S3_BUCKET = 's3chatbot.com'
        BUILD_DIR = 's3chatbot-frontend/build' // Corrected path
        REACT_APP_DIR = 's3chatbot-frontend' // Define the React app directory
    }

    stages {
        stage('Checkout') {
            steps {
                // Removed the redundant git step
                echo "Repository already checked out by Declarative Checkout SCM"
            }
        }

        stage('Install Dependencies') {
            steps {
                sh "cd ${REACT_APP_DIR} && npm install"
            }
        }

        stage('Build') {
            steps {
                sh "cd ${REACT_APP_DIR} && npm run build"
            }
        }

        stage('Deploy to S3') {
            steps {
                script {
                    sh "aws s3 sync ${BUILD_DIR} s3://${S3_BUCKET} --delete --acl public-read --region your-aws-region"
                }
            }
        }
    }
}