pipeline {
    agent { docker 'jenkins-s3chatbot:latest' }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Terraform Init') {
            steps {
                dir('IAC') {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                dir('IAC') {
                    sh 'terraform plan -no-color'
                }
            }
        }
        // More stages to come
    }
}