pipeline {
    agent any // Runs directly on the Jenkins container

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Prepare Lambda Layer') {
            steps {
                dir('IAC/shared_dependencies') {
                    sh '''
                    mkdir -p python/lib/python3.9/site-packages
                    pip install -r requirements.txt -t python/lib/python3.9/site-packages
                    zip -r lambda_layer_payload.zip python
                    '''
                }
            }
        }

stage('Package Data Ingestion Lambda') {
    steps {
        dir('IAC/data_ingestion_lambda') {
            sh 'mkdir -p package'
            sh 'cp ../../data_ingestion_lambda.py package/'  // Copy only the Lambda function
            sh 'cd package && zip -r ../data_ingestion_lambda_payload.zip .'  // Create ZIP package
        }
    }
}

stage('Package Bedrock Proxy Lambda') {
    steps {
        dir('IAC/bedrock_proxy_lambda') {
            sh 'mkdir -p package'
            sh 'cp ../../bedrock_proxy_lambda.py package/'  // Copy only the Lambda function
            sh 'cd package && zip -r ../bedrock_proxy_lambda_payload.zip .'  // Create ZIP package
        }
    }
}

        stage('Terraform Init') {
            steps {
                dir('IAC') {
                    sh 'terraform init'
                }
            }
        }

        // stage('Terraform Apply') {
        //     steps {
        //         dir('IAC') {
        //             sh 'terraform apply -auto-approve'
        //         }
        //     }
        // }
    }
}